import {
  lstat,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  symlink,
  utimes,
  writeFile,
} from "node:fs/promises";
import * as path from "node:path";

import { afterEach, describe, expect, it, vi } from "vitest";

import { makeTempDir } from "../../../test-utils/tempDir";
import PluginPersistor, { PluginFileConflict, type PluginFormat } from "./PluginPersistor";

const paths = vi.hoisted(() => ({ pluginDir: "", dataDir: "", format: "fallout4" }));

vi.mock("./gameSupport", () => ({
  gameSupported: (gameId: string) => gameId === "skyrimse",
  gameDataPath: () => paths.dataDir,
  pluginPath: () => paths.pluginDir,
  pluginFormat: () => paths.format,
  nativePlugins: () => [],
}));

const HEADER = "# Automatically generated by Vortex\r\n";
const OLD_ORDER = HEADER + "Old.esp\r\nParked.esp\r\n";
const persistors: PluginPersistor[] = [];

interface IScenario {
  format?: PluginFormat;
  pluginFile?: string;
  orderFile?: string;
  extraFiles?: Record<string, string>;
}

async function arrange(spec: IScenario = {}) {
  const root = await makeTempDir("vortex-plugin-lists-");
  paths.pluginDir = path.join(root, "settings");
  paths.dataDir = path.join(root, "Data");
  paths.format = spec.format ?? "fallout4";
  const pluginFile = path.join(paths.pluginDir, spec.pluginFile ?? "plugins.txt");
  const orderFile = path.join(paths.pluginDir, spec.orderFile ?? "loadorder.txt");
  await Promise.all([mkdir(paths.pluginDir), mkdir(paths.dataDir)]);
  await Promise.all([
    writeFile(
      pluginFile,
      HEADER + (paths.format === "original" ? "Old.esp\r\n" : "*Old.esp\r\n"),
      "latin1",
    ),
    writeFile(orderFile, OLD_ORDER, "utf8"),
    writeFile(path.join(paths.dataDir, "Old.esp"), "TES4"),
    writeFile(path.join(paths.dataDir, "Parked.esp"), "TES4"),
    ...Object.entries(spec.extraFiles ?? {}).map(([name, content]) =>
      writeFile(path.join(paths.pluginDir, name), content, "latin1"),
    ),
  ]);
  const onError = vi.fn();
  const persistor = new PluginPersistor(onError, () => true, vi.fn());
  persistors.push(persistor);
  persistor.setResetCallback(vi.fn(() => Promise.resolve()));
  persistor.setKnownPlugins({ "old.esp": "Old.esp", "parked.esp": "Parked.esp" });
  await persistor.loadFiles("skyrimse");
  // Wait for the initial debounced write before a test makes an external change.
  await persistor.loadFiles("unsupported");
  return { root, pluginDir: paths.pluginDir, pluginFile, orderFile, persistor, onError };
}

afterEach(async () => {
  for (const persistor of persistors.splice(0)) {
    await persistor.disable();
  }
});

describe.skipIf(process.platform !== "linux")("Linux Bethesda plugin lists", () => {
  it.each(["fallout4", "original"] as const)(
    "reads and updates existing mixed-case filenames in %s format",
    async (format) => {
      const { pluginDir, pluginFile, orderFile, persistor, onError } = await arrange({
        format,
        pluginFile: "Plugins.TXT",
        orderFile: "LoadOrder.txt",
      });

      expect(persistor.entry("old.esp").enabled).toBe(true);
      await persistor.syncFromState("skyrimse", {
        "old.esp": { enabled: false, loadOrder: 1 },
        "parked.esp": { enabled: true, loadOrder: 0 },
      });

      const enabled = await readFile(pluginFile, "latin1");
      expect(enabled).toContain(format === "original" ? "Parked.esp" : "*Parked.esp");
      expect(enabled).not.toContain("*Old.esp");
      expect(await readFile(orderFile, "utf8")).toBe(HEADER + "Parked.esp\r\nOld.esp");
      expect((await readdir(pluginDir)).sort()).toEqual(["LoadOrder.txt", "Plugins.TXT"]);
      expect(onError).not.toHaveBeenCalled();
    },
  );

  it("prefers exact canonical filenames without changing other case variants", async () => {
    const foreign = "# Other profile\r\n*Different.esp\r\n";
    const { pluginDir, persistor } = await arrange({ extraFiles: { "Plugins.txt": foreign } });

    expect(persistor.entry("old.esp").enabled).toBe(true);
    expect(await readFile(path.join(pluginDir, "Plugins.txt"), "latin1")).toBe(foreign);
    expect((await readdir(pluginDir)).sort()).toEqual([
      "Plugins.txt",
      "loadorder.txt",
      "plugins.txt",
    ]);
  });

  it("creates canonical list files when the game's settings directory is new", async () => {
    const { root, persistor, onError } = await arrange();
    await persistor.disable();
    const pluginDir = path.join(root, "new-settings");
    paths.pluginDir = pluginDir;

    await persistor.loadFiles("skyrimse");
    await persistor.syncFromState("skyrimse", { "old.esp": { enabled: true, loadOrder: 0 } });

    expect((await readdir(pluginDir)).sort()).toEqual(["loadorder.txt", "plugins.txt"]);
    expect(await readFile(path.join(pluginDir, "plugins.txt"), "latin1")).toContain("*Old.esp");
    expect(onError).not.toHaveBeenCalled();
  });

  it("does not create or overwrite lists when existing filename casing is ambiguous", async () => {
    const other = "# Different order\r\n*Parked.esp\r\n";
    const { pluginDir, pluginFile, orderFile, persistor, onError } = await arrange({
      pluginFile: "Plugins.txt",
      extraFiles: { "PLUGINS.TXT": other },
    });

    await persistor.syncFromState("skyrimse", { "old.esp": { enabled: false, loadOrder: 0 } });

    expect((await readdir(pluginDir)).sort()).toEqual([
      "PLUGINS.TXT",
      "Plugins.txt",
      "loadorder.txt",
    ]);
    expect(await readFile(pluginFile, "latin1")).toBe(HEADER + "*Old.esp\r\n");
    expect(await readFile(path.join(pluginDir, "PLUGINS.TXT"), "latin1")).toBe(other);
    expect(await readFile(orderFile, "utf8")).toBe(OLD_ORDER);
    expect(onError).toHaveBeenCalledWith(
      "failed to read plugin list",
      expect.objectContaining({ message: expect.stringContaining("Plugins.txt") }),
      { allowReport: false },
    );

    await rm(path.join(pluginDir, "PLUGINS.TXT"));
    await persistor.loadFiles("skyrimse");
    await persistor.loadFiles("unsupported");

    expect(persistor.entry("old.esp").enabled).toBe(true);
    expect((await readdir(pluginDir)).sort()).toEqual(["Plugins.txt", "loadorder.txt"]);
  });

  it.each(["plugins.txt", "loadorder.txt"])(
    "checks both paths before writing when %s becomes ambiguous",
    async (fileName) => {
      const { pluginDir, pluginFile, orderFile, persistor, onError } = await arrange();
      const before = await Promise.all([
        readFile(pluginFile, "latin1"),
        readFile(orderFile, "utf8"),
      ]);
      await rm(path.join(pluginDir, fileName));
      const first = fileName === "plugins.txt" ? "Plugins.txt" : "LoadOrder.txt";
      const second = fileName.toUpperCase();
      await writeFile(path.join(pluginDir, first), "# First list\r\nOld.esp\r\n");
      await writeFile(path.join(pluginDir, second), "# Second list\r\nParked.esp\r\n");

      await persistor.syncFromState("skyrimse", { "old.esp": { enabled: false, loadOrder: 0 } });

      const untouched = fileName === "plugins.txt" ? orderFile : pluginFile;
      expect(await readFile(untouched, fileName === "plugins.txt" ? "utf8" : "latin1")).toBe(
        before[fileName === "plugins.txt" ? 1 : 0],
      );
      expect(await readFile(path.join(pluginDir, first), "utf8")).toBe(
        "# First list\r\nOld.esp\r\n",
      );
      expect(await readFile(path.join(pluginDir, second), "utf8")).toBe(
        "# Second list\r\nParked.esp\r\n",
      );
      expect(await readdir(pluginDir)).not.toContain(fileName);
      expect(onError).toHaveBeenCalledWith(
        "failed to write plugin list",
        expect.objectContaining({ message: expect.stringContaining(second) }),
        { allowReport: false },
      );
    },
  );

  it("keeps a mixed-case file symlink and updates its existing target", async () => {
    const { root, pluginDir, pluginFile, persistor } = await arrange({ pluginFile: "Plugins.txt" });
    const target = path.join(root, "profile-plugins.txt");
    await persistor.disable();
    await rename(pluginFile, target);
    await symlink(target, pluginFile);
    await persistor.loadFiles("skyrimse");
    await persistor.syncFromState("skyrimse", { "old.esp": { enabled: false, loadOrder: 0 } });

    expect((await lstat(pluginFile)).isSymbolicLink()).toBe(true);
    expect(await readFile(target, "latin1")).not.toContain("*Old.esp");
    expect(await readdir(pluginDir)).not.toContain("plugins.txt");
  });

  it("observes a rewrite of an existing mixed-case plugin list", async () => {
    const { pluginFile, persistor } = await arrange({ pluginFile: "Plugins.txt" });
    const asked = vi.fn(() => Promise.resolve("keep" as const));
    persistor.setExternalChangeCallback(asked);
    await writeFile(pluginFile, "# Another tool\r\n*Parked.esp\r\n", "latin1");
    const future = new Date(Date.now() + 5_000);
    await utimes(pluginFile, future, future);

    await vi.waitFor(
      () => {
        expect(asked).toHaveBeenCalledWith(PluginFileConflict.ForeignChange);
        expect(persistor.entry("parked.esp").enabled).toBe(true);
      },
      { timeout: 3_000 },
    );
  });

  it.each(["plugins.txt", "Plugins.txt"])(
    "observes atomic replacement of %s even with an older mtime and preserves it pending a choice",
    async (pluginName) => {
      const { pluginFile, persistor } = await arrange({ pluginFile: pluginName });
      let choose: (choice: "keep" | "revert") => void;
      const asked = vi.fn(
        () =>
          new Promise<"keep" | "revert">((resolve) => {
            choose = resolve;
          }),
      );
      persistor.setExternalChangeCallback(asked);
      const replaced = "# Another tool\r\n*Parked.esp\r\n";
      const tempFile = pluginFile + ".tmp";
      await writeFile(tempFile, replaced, "latin1");
      const old = new Date("2000-01-01T00:00:00Z");
      await utimes(tempFile, old, old);
      await rename(tempFile, pluginFile);

      await vi.waitFor(
        () => {
          expect(asked).toHaveBeenCalledWith(PluginFileConflict.ForeignChange);
        },
        { timeout: 3_000 },
      );
      await persistor.syncFromState("skyrimse", { "old.esp": { enabled: false, loadOrder: 0 } });
      expect(await readFile(pluginFile, "latin1")).toBe(replaced);

      choose("keep");
      await vi.waitFor(() => {
        expect(persistor.entry("parked.esp").enabled).toBe(true);
      });
    },
  );

  it("refreshes file spelling after an external rename", async () => {
    const { pluginDir, pluginFile, persistor } = await arrange();
    const replacement = path.join(pluginDir, "PLUGINS.TXT");
    const tempFile = pluginFile + ".tmp";
    const asked = vi.fn(() => Promise.resolve("keep" as const));
    persistor.setExternalChangeCallback(asked);
    await writeFile(tempFile, "# Another tool\r\n*Parked.esp\r\n", "latin1");
    const old = new Date("2000-01-01T00:00:00Z");
    await utimes(tempFile, old, old);
    await rename(tempFile, replacement);
    await rm(pluginFile);

    await vi.waitFor(
      () => {
        expect(persistor.entry("parked.esp").enabled).toBe(true);
      },
      { timeout: 3_000 },
    );
    await persistor.syncFromState("skyrimse", { "parked.esp": { enabled: false, loadOrder: 0 } });
    expect(await readdir(pluginDir)).not.toContain("plugins.txt");
    expect(await readFile(replacement, "latin1")).not.toContain("*Parked.esp");
  });

  it("observes replacement of the original format's load-order file with an older mtime", async () => {
    const { orderFile, persistor } = await arrange({
      format: "original",
      orderFile: "LoadOrder.TXT",
    });
    const asked = vi.fn(() => Promise.resolve("keep" as const));
    persistor.setExternalChangeCallback(asked);
    const tempFile = orderFile + ".tmp";
    await writeFile(tempFile, "# Another tool\r\nParked.esp\r\nOld.esp\r\n", "utf8");
    const old = new Date("2000-01-01T00:00:00Z");
    await utimes(tempFile, old, old);
    await rename(tempFile, orderFile);

    await vi.waitFor(
      () => {
        expect(asked).toHaveBeenCalledWith(PluginFileConflict.ForeignChange);
        expect(persistor.entry("parked.esp").loadOrder).toBe(0);
        expect(persistor.entry("old.esp").loadOrder).toBe(1);
        expect(persistor.entry("old.esp").enabled).toBe(true);
      },
      { timeout: 3_000 },
    );
  });
});
